@startuml

skinparam class {
  BackgroundColor #ebebeb
  ArrowColor      #333
  BorderColor     #000
}

skinparam lineType ortho

package builtins {
  class builtins.RuntimeError {}
  class builtins.str {}
  class builtins.dict {}
}

package md.python {
  interface md.python.PythonExceptionInterface {}
}

package md.python.dict {
  interface DictExceptionInterface extends md.python.PythonExceptionInterface {}
  interface MergeDictionaryInterface {
    + merge(left: dict, right: dict) -> dict
  }
  class DefaultMergeDictionary implements MergeDictionaryInterface {
    + merge(left: dict, right: dict) -> dict
  }

  class CaseInsensitiveDictKey extends builtins.str {}
  class CaseInsensitiveDict <V of Any> extends builtins.dict {
    + __init__(dict_: Optional[Dict[Hashable, V]] = None, **kwargs: V) -> None
    + __setitem__(key: Any, value: V) -> None
    + __getitem__(key: Any) -> V
    + __delitem__(key: Any) -> None
  }

  CaseInsensitiveDict *-right-> CaseInsensitiveDictKey
}

@enduml
